postgres:
  hostname: postgres
  restart: always
  image: postgres:latest
  environment:
    - POSTGRES_DB=bge
    - POSTGRES_USER=bge
    - POSTGRES_PASSWORD=ribszijngoed
  volumes:
    - ./sql/:/docker-entrypoint-initdb.d/

flask:
  build: .
  links:
    - postgres:postgres
  ports:
    - 8000:8000
  expose:
    - 8000
  volumes:
    - ./sql/:/docker-entrypoint-initdb.d/
